<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<AssemblyTitle>WpfConstrols.Demo</AssemblyTitle>
	<Description></Description>
	<Product>WpfConstrols.Demo</Product>
	<Copyright>Copyright © 2025</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoCompleteTextBox\AutoCompleteTextBox.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\fechar.png" />
    <Resource Include="Images\maximizar.png" />
    <Resource Include="Images\minimizar.png" />
  </ItemGroup>
  <ItemGroup>
	<Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes">
      <Version>1.5.0.523</Version>
    </PackageReference>
    <PackageReference Include="MVVMHelpers">
      <Version>2012.4.20.3</Version>
    </PackageReference>
  </ItemGroup>
</Project>